# -*- coding: utf-8 -*-
"""Active_Products_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9eSS_vMPYZV603UizDfnXO5L9tGfIK2
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import io

# ==========================================
# PAGE CONFIGURATION & UI SETUP
# ==========================================
st.set_page_config(page_title="Catalog Integrity Check", layout="wide")

st.title("🛒 Catalog Integrity Checker")
st.markdown("""
**Operational Guardrail:** Upload the latest active exports from Shopify and Dynamics 365.
This tool cross-references inventory and lifecycle statuses to generate an instant bulk-import fix file, preventing phantom inventory and overselling.
""")

st.divider()

# ==========================================
# SIDEBAR CONFIGURATION
# ==========================================
with st.sidebar:
    st.header("⚙️ Configuration")
    inventory_buffer = st.number_input(
        "Inventory Buffer Threshold",
        min_value=0, value=1,
        help="If D365 stock is at or below this number, the item will be drafted."
    )
    discontinued_keyword = st.text_input(
        "D365 Discontinued Keyword",
        value="Discontinued",
        help="The exact text D365 uses for dead items."
    )

# ==========================================
# FILE UPLOADERS
# ==========================================
col1, col2 = st.columns(2)

with col1:
    st.subheader("1. Upload Shopify Export")
    shopify_file = st.file_uploader("Upload shopify_export.csv", type=['csv'])

with col2:
    st.subheader("2. Upload D365 Export")
    d365_file = st.file_uploader("Upload d365_export.csv", type=['csv'])

# ==========================================
# EXECUTION LOGIC
# ==========================================
if shopify_file is not None and d365_file is not None:

    # Read the files
    try:
        df_shopify = pd.read_csv(shopify_file)
        df_d365 = pd.read_csv(d365_file)
    except Exception as e:
        st.error(f"Error reading files: {e}")
        st.stop()

    # Verify required columns exist (using the dummy names from our previous test)
    req_shopify_cols = ['Handle', 'SKU', 'Status']
    req_d365_cols = ['SKU', 'Available_Quantity', 'Item_Status']

    missing_shopify = [col for col in req_shopify_cols if col not in df_shopify.columns]
    missing_d365 = [col for col in req_d365_cols if col not in df_d365.columns]

    if missing_shopify or missing_d365:
        st.error("⚠️ Column Mismatch Detected!")
        if missing_shopify:
            st.write(f"Missing in Shopify export: {missing_shopify}")
        if missing_d365:
            st.write(f"Missing in D365 export: {missing_d365}")
        st.info("Please ensure your CSVs match the required formatting.")
        st.stop()

    if st.button("🚀 Run Integrity Check", use_container_width=True, type="primary"):
        with st.spinner("Crunching data..."):

            # Merge on SKU
            df_merged = pd.merge(df_shopify, df_d365, on='SKU', how='inner')

            # Logic Engine
            def determine_new_status(row):
                if str(row['Status']).strip().lower() == 'active':
                    # Rule 1: Discontinued
                    if str(row['Item_Status']).strip().lower() == discontinued_keyword.lower():
                        return 'Archived'
                    # Rule 2: Stock Risk
                    try:
                        if float(row['Available_Quantity']) <= inventory_buffer:
                            return 'Draft'
                    except ValueError:
                        pass
                return None

            df_merged['New_Status'] = df_merged.apply(determine_new_status, axis=1)
            df_action_needed = df_merged[df_merged['New_Status'].notnull()].copy()

            # ==========================================
            # DASHBOARD & RESULTS
            # ==========================================
            st.divider()
            st.subheader("📊 Executive Summary")

            metric_col1, metric_col2, metric_col3 = st.columns(3)

            total_evaluated = len(df_merged)
            total_drafted = len(df_action_needed[df_action_needed['New_Status'] == 'Draft'])
            total_archived = len(df_action_needed[df_action_needed['New_Status'] == 'Archived'])

            metric_col1.metric("Total SKUs Evaluated", total_evaluated)
            metric_col2.metric("Drafted (Stock Risk)", total_drafted, delta="-Overselling Prevented", delta_color="normal")
            metric_col3.metric("Archived (Discontinued)", total_archived, delta="-Cleaned Catalog", delta_color="normal")

            # Generate the Fix File
            df_final = df_action_needed[['Handle', 'New_Status']].copy()
            df_final.rename(columns={'New_Status': 'Status'}, inplace=True)

            if len(df_final) > 0:
                st.success(f"**{len(df_final)} Anomalies Detected.** The fix file is ready for Shopify import.")

                # Convert DF to CSV in memory for download button
                csv_buffer = io.StringIO()
                df_final.to_csv(csv_buffer, index=False)
                csv_data = csv_buffer.getvalue()

                date_str = datetime.now().strftime("%Y%m%d_%H%M")
                filename = f"Shopify_Import_Fix_{date_str}.csv"

                # Layout for download button and data preview
                dl_col, preview_col = st.columns([1, 2])
                with dl_col:
                    st.download_button(
                        label="⬇️ Download Shopify Import File",
                        data=csv_data,
                        file_name=filename,
                        mime='text/csv',
                        type="primary"
                    )
                with preview_col:
                    with st.expander("Preview Actionable Items"):
                        st.dataframe(df_action_needed[['SKU', 'Handle', 'Available_Quantity', 'Item_Status', 'New_Status']], use_container_width=True)
            else:
                st.success("✅ No anomalies found. The catalog is perfectly synced with D365.")

"""### Generate `requirements.txt`

This cell will create a `requirements.txt` file, which lists all the Python packages required by your application. This is crucial for deploying your app (e.g., to Streamlit Community Cloud) or for anyone else trying to run your code.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas

"""### Create `app.py`

This cell writes your Streamlit application code into a file named `app.py`. This is the main file that Streamlit Community Cloud will look for when deploying your app.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from datetime import datetime
# import io
# 
# # ==========================================
# # PAGE CONFIGURATION & UI SETUP
# # ==========================================
# st.set_page_config(page_title="Catalog Integrity Check", layout="wide")
# 
# st.title("🛒 Catalog Integrity Checker")
# st.markdown("""
# **Operational Guardrail:** Upload the latest active exports from Shopify and Dynamics 365.
# This tool cross-references inventory and lifecycle statuses to generate an instant bulk-import fix file, preventing phantom inventory and overselling.
# """)
# 
# st.divider()
# 
# # ==========================================
# # SIDEBAR CONFIGURATION
# # ==========================================
# with st.sidebar:
#     st.header("⚙️ Configuration")
#     inventory_buffer = st.number_input(
#         "Inventory Buffer Threshold",
#         min_value=0, value=1,
#         help="If D365 stock is at or below this number, the item will be drafted."
#     )
#     discontinued_keyword = st.text_input(
#         "D365 Discontinued Keyword",
#         value="Discontinued",
#         help="The exact text D365 uses for dead items."
#     )
# 
# # ==========================================
# # FILE UPLOADERS
# # ==========================================
# col1, col2 = st.columns(2)
# 
# with col1:
#     st.subheader("1. Upload Shopify Export")
#     shopify_file = st.file_uploader("Upload shopify_export.csv", type=['csv'])
# 
# with col2:
#     st.subheader("2. Upload D365 Export")
#     d365_file = st.file_uploader("Upload d365_export.csv", type=['csv'])
# 
# # ==========================================
# # EXECUTION LOGIC
# # ==========================================
# if shopify_file is not None and d365_file is not None:
# 
#     # Read the files
#     try:
#         df_shopify = pd.read_csv(shopify_file)
#         df_d365 = pd.read_csv(d365_file)
#     except Exception as e:
#         st.error(f"Error reading files: {e}")
#         st.stop()
# 
#     # Verify required columns exist (using the dummy names from our previous test)
#     req_shopify_cols = ['Handle', 'SKU', 'Status']
#     req_d365_cols = ['SKU', 'Available_Quantity', 'Item_Status']
# 
#     missing_shopify = [col for col in req_shopify_cols if col not in df_shopify.columns]
#     missing_d365 = [col for col in req_d365_cols if col not in df_d365.columns]
# 
#     if missing_shopify or missing_d365:
#         st.error("⚠️ Column Mismatch Detected!")
#         if missing_shopify:
#             st.write(f"Missing in Shopify export: {missing_shopify}")
#         if missing_d365:
#             st.write(f"Missing in D365 export: {missing_d365}")
#         st.info("Please ensure your CSVs match the required formatting.")
#         st.stop()
# 
#     if st.button("🚀 Run Integrity Check", use_container_width=True, type="primary"):
#         with st.spinner("Crunching data..."):
# 
#             # Merge on SKU
#             df_merged = pd.merge(df_shopify, df_d365, on='SKU', how='inner')
# 
#             # Logic Engine
#             def determine_new_status(row):
#                 if str(row['Status']).strip().lower() == 'active':
#                     # Rule 1: Discontinued
#                     if str(row['Item_Status']).strip().lower() == discontinued_keyword.lower():
#                         return 'Archived'
#                     # Rule 2: Stock Risk
#                     try:
#                         if float(row['Available_Quantity']) <= inventory_buffer:
#                             return 'Draft'
#                     except ValueError:
#                         pass
#                 return None
# 
#             df_merged['New_Status'] = df_merged.apply(determine_new_status, axis=1)
#             df_action_needed = df_merged[df_merged['New_Status'].notnull()].copy()
# 
#             # ==========================================
#             # DASHBOARD & RESULTS
#             # ==========================================
#             st.divider()
#             st.subheader("📊 Executive Summary")
# 
#             metric_col1, metric_col2, metric_col3 = st.columns(3)
# 
#             total_evaluated = len(df_merged)
#             total_drafted = len(df_action_needed[df_action_needed['New_Status'] == 'Draft'])
#             total_archived = len(df_action_needed[df_action_needed['New_Status'] == 'Archived'])
# 
#             metric_col1.metric("Total SKUs Evaluated", total_evaluated)
#             metric_col2.metric("Drafted (Stock Risk)", total_drafted, delta="-Overselling Prevented", delta_color="normal")
#             metric_col3.metric("Archived (Discontinued)", total_archived, delta="-Cleaned Catalog", delta_color="normal")
# 
#             # Generate the Fix File
#             df_final = df_action_needed[['Handle', 'New_Status']].copy()
#             df_final.rename(columns={'New_Status': 'Status'}, inplace=True)
# 
#             if len(df_final) > 0:
#                 st.success(f"**{len(df_final)} Anomalies Detected.** The fix file is ready for Shopify import.")
# 
#                 # Convert DF to CSV in memory for download button
#                 csv_buffer = io.StringIO()
#                 df_final.to_csv(csv_buffer, index=False)
#                 csv_data = csv_buffer.getvalue()
# 
#                 date_str = datetime.now().strftime("%Y%m%d_%H%M")
#                 filename = f"Shopify_Import_Fix_{date_str}.csv"
# 
#                 # Layout for download button and data preview
#                 dl_col, preview_col = st.columns([1, 2])
#                 with dl_col:
#                     st.download_button(
#                         label="⬇️ Download Shopify Import File",
#                         data=csv_data,
#                         file_name=filename,
#                         mime='text/csv',
#                         type="primary"
#                     )
#                 with preview_col:
#                     with st.expander("Preview Actionable Items"):
#                         st.dataframe(df_action_needed[['SKU', 'Handle', 'Available_Quantity', 'Item_Status', 'New_Status']], use_container_width=True)
#             else:
#                 st.success("✅ No anomalies found. The catalog is perfectly synced with D365.")

"""### Create `README.md`

This file provides a general overview of your project, how to set it up, and how to run your Streamlit application.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # Catalog Integrity Checker
# 
# This Streamlit application helps ensure the integrity of your product catalog by cross-referencing inventory and lifecycle statuses between Shopify and Dynamics 365 exports. It generates a bulk-import fix file for Shopify, preventing issues like phantom inventory and overselling.
# 
# ## Features
# - Upload Shopify and Dynamics 365 CSV exports.
# - Configure inventory buffer thresholds and discontinued item keywords.
# - Identifies items that need to be 'Drafted' (due to low stock) or 'Archived' (if discontinued).
# - Generates a downloadable CSV file ready for Shopify import to apply fixes.
# - Provides an executive summary of anomalies detected.
# 
# ## How to Run Locally
# 
# 1.  **Clone the repository**:
#     ```bash
#     git clone <your-repository-url>
#     cd <your-repository-name>
#     ```
# 
# 2.  **Create a virtual environment (recommended)**:
#     ```bash
#     python -m venv venv
#     source venv/bin/activate  # On Windows, use `venv\Scripts\activate`
#     ```
# 
# 3.  **Install dependencies**:
#     ```bash
#     pip install -r requirements.txt
#     ```
# 
# 4.  **Run the Streamlit application**:
#     ```bash
#     streamlit run app.py
#     ```
# 
#     Your browser will open to the Streamlit app.
# 
# ## How to Deploy to Streamlit Community Cloud
# 
# 1.  **Push your code to GitHub**: Ensure all files (`app.py`, `requirements.txt`, `README.md`, `LICENSE`, `.gitignore`) are pushed to a public GitHub repository.
# 2.  **Go to Streamlit Community Cloud**: Log in at [share.streamlit.io](https://share.streamlit.io/).
# 3.  **Deploy a new app**: Select 'New app' and connect your GitHub repository. Choose `app.py` as your main file.
# 4.  **Launch**: Click deploy, and your application will be live!

"""### Create `LICENSE`

This file specifies the legal terms under which your project can be used and distributed. The MIT License is a common choice for open-source projects.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile LICENSE
# MIT License
# 
# Copyright (c) 2024 Your Name (or Project Name)
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""### Create `.gitignore`

This file tells Git which files or directories to ignore when you make a commit. This is useful for excluding temporary files, virtual environments, or sensitive data.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile .gitignore
# # Python
# __pycache__/
# *.pyc
# *.pyo
# *.pyd
# .Python/
# 
# # Virtual environment
# virtualenv/
# virt/
# vEnv/
# vf/
# .venv/
# venv/
# 
# # IDEs and Editors
# .vscode/
# .idea/
# 
# # Jupyter/Colab specific
# .ipynb_checkpoints/
# 
# # Streamlit specific
# .streamlit/
# 
# # Data files (if any generated or uploaded locally)
# *.csv
# *.xlsx
# *.xls
# 
# # Specific to this project
# shopify_export.csv
# d365_export.csv

pip install streamlit

pip install streamlit pandas